### ISSUE TITLE
Double Loading on Nearby Streams

### ISSUE THREAD

**Issue by ericaddison** [ericaddison/APT_miniProject_Android#24]
Maybe the same problem we saw before?

**Comment by psigourney** [comment]
Are you getting images loading twice the first time visiting Nearby, or after other actions?

Is this on the current Master branch?

```
    @Override
    protected void onStart() {
        super.onStart();
        adapter.clear();
    }
```
Might need to add the adapter.clear() to the top of the handleNewLocation function instead of onStart.  So it the location updates dynamically (but onStart isn't called), the image queue is cleared before it's rebuilt.

edit: added pull request.
